export const WASABI_BUCKET_NAME = 'WASABI_BUCKET_NAME';
export const BUCKET_PATH_KEY = 'BUCKET_PATH_KEY';
export const DOWNLOAD_DESTINATION_PATH = 'DOWNLOAD_DESTINATION_PATH';

export const WASABI_BUCKET_REGION = 'WASABI_BUCKET_REGION';
export const WASABI_BUCKET_ENDPOINT = 'WASABI_BUCKET_ENDPOINT';
export const WASABI_ACCESS_KEY = 'WASABI_ACCESS_KEY';
export const WASABI_SECRET_KEY = 'WASABI_SECRET_KEY';
